export const birdImages: Record<string, string> = {
  "American Crow": "/birds/american-crow.jpg",
  "American Goldfinch": "/birds/american-goldfinch.jpg",
  "American Kestrel": "/birds/american-kestrel.jpg",
  "American Robin": "/birds/american-robin.jpg",
  "American White Pelican": "/birds/american-white-pelican.jpg",
  "American Woodcock": "/birds/american-woodcock.jpg",
  "Bald Eagle": "/birds/bald-eagle.jpg",
  "Baltimore Oriole": "/birds/baltimore-oriole.jpg",
  "Barn Swallow": "/birds/barn-swallow.jpg",
  "Barred Owl": "/birds/barred-owl.jpg",
  "Belted Kingfisher": "/birds/belted-kingfisher.jpg",
  "Black-capped Chickadee": "/birds/black-capped-chickadee.jpg",
  "Blue Jay": "/birds/blue-jay.jpg",
  "Blue-gray Gnatcatcher": "/birds/blue-gray-gnatcatcher.jpg",
  "Brown Creeper": "/birds/brown-creeper.jpg",
  "Brown-headed Cowbird": "/birds/brown-headed-cowbird.jpg",
  "Brown Thrasher": "/birds/brown-thrasher.jpg",
  "Canada Goose": "/birds/canada-goose.jpg",
  "Cedar Waxwing": "/birds/cedar-waxwing.jpg",
  "Chipping Sparrow": "/birds/chipping-sparrow.jpg",
  "Common Grackle": "/birds/common-grackle.jpg",
  "Common Merganser": "/birds/common-merganser.jpg",
  "Common Yellowthroat": "/birds/common-yellowthroat.jpg",
  "Cooper's Hawk": "/birds/coopers-hawk.jpg",
  "Dark-eyed Junco": "/birds/dark-eyed-junco.jpg",
  "Double-crested Cormorant": "/birds/double-crested-cormorant.jpg",
  "Downy Woodpecker": "/birds/downy-woodpecker.jpg",
  "Eastern Bluebird": "/birds/eastern-bluebird.jpg",
  "Eastern Phoebe": "/birds/eastern-phoebe.jpg",
  "Eastern Towhee": "/birds/eastern-towhee.jpg",
  "European Starling": "/birds/european-starling.jpg",
  "Gray Catbird": "/birds/gray-catbird.jpg",
  "Great Blue Heron": "/birds/great-blue-heron.jpg",
  "Great Egret": "/birds/great-egret.jpg",
  "Great Horned Owl": "/birds/great-horned-owl.jpg",
  "Hairy Woodpecker": "/birds/hairy-woodpecker.jpg",
  "House Finch": "/birds/house-finch.jpg",
  "House Sparrow": "/birds/house-sparrow.jpg",
  "Mourning Dove": "/birds/mourning-dove.jpg",
  "Northern Flicker": "/birds/northern-flicker.jpg",
  "Ruby-throated Hummingbird": "/birds/ruby-throated-hummingbird.jpg",
  "Sandhill Crane": "/birds/sandhill-crane.jpg",
  "White-breasted Nuthatch": "/birds/white-breasted-nuthatch.jpg",
};
