export const birds = [
  "American Crow",
  "American Goldfinch",
  "American Robin",
  "American White Pelican",
  "Black-capped Chickadee",
  "Blue Jay",
  "Brown-headed Cowbird",
  "Canada Goose",
  "Common Grackle",
  "Dark-eyed Junco",
  "Downy Woodpecker",
  "European Starling",
  "Great Blue Heron",
  "House Finch",
  "House Sparrow",
  "Killdeer",
  "Mallard",
  "Mourning Dove",
  "Northern Cardinal",
  "Northern Flicker",
  "Northern House Wren",
  "Red-bellied Woodpecker",
  "Red-tailed Hawk",
  "Red-winged Blackbird",
  "Ring-billed Gull",
  "Ruby-throated Hummingbird",
  "Sandhill Crane",
  "White-breasted Nuthatch",
  "Wild Turkey",
];
