export const birdImages: Record<string, string> = {
  "American Goldfinch": "/birds/american-goldfinch.jpg",
  "American Robin": "/birds/american-robin.jpg",
  "Blue Jay": "/birds/blue-jay.jpg",
  "Black-capped Chickadee": "/birds/black-capped-chickadee.jpg",
  "Brown-headed Cowbird": "/birds/brown-headed-cowbird.jpg",
  "Common Grackle": "/birds/common-grackle.jpg",
  "Cooper's Hawk": "/birds/coopers-hawk.jpg",
  "Downy Woodpecker": "/birds/downy-woodpecker.jpg",
  "Hairy Woodpecker": "/birds/hairy-woodpecker.jpg",
  "House Finch": "/birds/house-finch.jpg",
  "House Sparrow": "/birds/house-sparrow.jpg",
  "Mourning Dove": "/birds/mourning-dove.jpg",
  "Ruby-throated Hummingbird": "/birds/ruby-throated-hummingbird.jpg",
  "Sandhill Crane": "/birds/sandhill-crane.jpg",
};
