export const birdImages: Record<string, string> = {
  "American Crow": "/birds/american-crow.jpg",
  "American Goldfinch": "/birds/american-goldfinch.jpg",
  "American Kestrel": "/birds/american-kestrel.jpg",
  "American Robin": "/birds/american-robin.jpg",
  "American White Pelican": "/birds/american-white-pelican.jpg",
  "American Woodcock": "/birds/american-woodcock.jpg",
  "Bald Eagle": "/birds/bald-eagle.jpg",
  "Baltimore Oriole": "/birds/baltimore-oriole.jpg",
  "Barn Swallow": "/birds/barn-swallow.jpg",
  "Barred Owl": "/birds/barred-owl.jpg",
  "Belted Kingfisher": "/birds/belted-kingfisher.jpg",
  "Black-capped Chickadee": "/birds/black-capped-chickadee.jpg",
  "Blue Jay": "/birds/blue-jay.jpg",
  "Blue-gray Gnatcatcher": "/birds/blue-gray-gnatcatcher.jpg",
  "Brown Creeper": "/birds/brown-creeper.jpg",
  "Brown-headed Cowbird": "/birds/brown-headed-cowbird.jpg",
  "Brown Thrasher": "/birds/brown-thrasher.jpg",
  "Canada Goose": "/birds/canada-goose.jpg",
  "Cedar Waxwing": "/birds/cedar-waxwing.jpg",
  "Chipping Sparrow": "/birds/chipping-sparrow.jpg",
  "Common Grackle": "/birds/common-grackle.jpg",
  "Common Merganser": "/birds/common-merganser.jpg",
  "Common Yellowthroat": "/birds/common-yellowthroat.jpg",
  "Cooper's Hawk": "/birds/coopers-hawk.jpg",
  "Dark-eyed Junco": "/birds/dark-eyed-junco.jpg",
  "Double-crested Cormorant": "/birds/double-crested-cormorant.jpg",
  "Downy Woodpecker": "/birds/downy-woodpecker.jpg",
  "Eastern Bluebird": "/birds/eastern-bluebird.jpg",
  "Eastern Phoebe": "/birds/eastern-phoebe.jpg",
  "Eastern Towhee": "/birds/eastern-towhee.jpg",
  "European Starling": "/birds/european-starling.jpg",
  "Gray Catbird": "/birds/gray-catbird.jpg",
  "Great Blue Heron": "/birds/great-blue-heron.jpg",
  "Great Egret": "/birds/great-egret.jpg",
  "Great Horned Owl": "/birds/great-horned-owl.jpg",
  "Green Heron": "/birds/green-heron.jpg",
  "Hairy Woodpecker": "/birds/hairy-woodpecker.jpg",
  "House Finch": "/birds/house-finch.jpg",
  "House Sparrow": "/birds/house-sparrow.jpg",
  "Indigo Bunting": "/birds/indigo-bunting.jpg",
  "Killdeer": "/birds/killdeer.jpg",
  "Mallard": "/birds/mallard.jpg",
  "Mourning Dove": "/birds/mourning-dove.jpg",
  "Northern Cardinal": "/birds/northern-cardinal.jpg",
  "Northern Flicker": "/birds/northern-flicker.jpg",
  "Northern House Wren": "/birds/northern-house-wren.jpg",
  "Northern Mockingbird": "/birds/northern-mockingbird.jpg",
  "Pileated Woodpecker": "/birds/pileated-woodpecker.jpg",
  "Pine Siskin": "/birds/pine-siskin.jpg",
  "Purple Finch": "/birds/purple-finch.jpg",
  "Red-bellied Woodpecker": "/birds/red-bellied-woodpecker.jpg",
  "Red-breasted Nuthatch": "/birds/red-breasted-nuthatch.jpg",
  "Red-headed Woodpecker": "/birds/red-headed-woodpecker.jpg",
  "Red-tailed Hawk": "/birds/red-tailed-hawk.jpg",
  "Red-winged Blackbird": "/birds/red-winged-blackbird.jpg",
  "Ring-billed Gull": "/birds/ring-billed-gull.jpg",
  "Rose-breasted Grosbeak": "/birds/rose-breasted-grosbeak.jpg",
  "Ruby-throated Hummingbird": "/birds/ruby-throated-hummingbird.jpg",
  "Sandhill Crane": "/birds/sandhill-crane.jpg",
  "Scarlet Tanager": "/birds/scarlet-tanager.jpg",
  "Song Sparrow": "/birds/song-sparrow.jpg",
  "Tree Swallow": "/birds/tree-swallow.jpg",
  "Turkey Vulture": "/birds/turkey-vulture.jpg",
  "White-breasted Nuthatch": "/birds/white-breasted-nuthatch.jpg",
  "White-throated Sparrow": "/birds/white-throated-sparrow.jpg",
  "Wild Turkey": "/birds/wild-turkey.jpg",
  "Wood Duck": "/birds/wood-duck.jpg",
  "Yellow Warbler": "/birds/yellow-warbler.jpg",
};
