export const birds = [
  "American Crow",
  "American Goldfinch",
  "American Kestrel",
  "American Robin",
  "American Tree Sparrow",
  "American White Pelican",
  "American Woodcock",
  "Bald Eagle",
  "Baltimore Oriole",
  "Barn Swallow",
  "Barred Owl",
  "Belted Kingfisher",
  "Black-capped Chickadee",
  "Blue Jay",
  "Blue-gray Gnatcatcher",
  "Blue-winged Teal",
  "Broad-winged Hawk",
  "Brown Creeper",
  "Brown Thrasher",
  "Brown-headed Cowbird",
  "Canada Goose",
  "Cedar Waxwing",
  "Chimney Swift",
  "Chipping Sparrow",
  "Common Grackle",
  "Common Merganser",
  "Common Nighthawk",
  "Common Yellowthroat",
  "Cooper's Hawk",
  "Dark-eyed Junco",
  "Double-crested Cormorant",
  "Downy Woodpecker",
  "Eastern Bluebird",
  "Eastern Kingbird",
  "Eastern Meadowlark",
  "Eastern Phoebe",
  "Eastern Screech-Owl",
  "Eastern Towhee",
  "European Starling",
  "Field Sparrow",
  "Fox Sparrow",
  "Gray Catbird",
  "Great Blue Heron",
  "Great Crested Flycatcher",
  "Great Egret",
  "Great Horned Owl",
  "Green Heron",
  "Green-winged Teal",
  "Hairy Woodpecker",
  "Hooded Merganser",
  "House Finch",
  "House Sparrow",
  "Indigo Bunting",
  "Killdeer",
  "Mallard",
  "Merlin",
  "Mourning Dove",
  "Northern Cardinal",
  "Northern Flicker",
  "Northern Harrier",
  "Northern House Wren",
  "Northern Mockingbird",
  "Peregrine Falcon",
  "Pileated Woodpecker",
  "Pine Siskin",
  "Purple Finch",
  "Red-bellied Woodpecker",
  "Red-breasted Nuthatch",
  "Red-eyed Vireo",
  "Red-headed Woodpecker",
  "Red-tailed Hawk",
  "Red-winged Blackbird",
  "Ring-billed Gull",
  "Ring-necked Duck",
  "Rose-breasted Grosbeak",
  "Ruby-throated Hummingbird",
  "Sandhill Crane",
  "Savannah Sparrow",
  "Scarlet Tanager",
  "Sharp-shinned Hawk",
  "Song Sparrow",
  "Spotted Sandpiper",
  "Swamp Sparrow",
  "Tree Swallow",
  "Turkey Vulture",
  "White-breasted Nuthatch",
  "White-crowned Sparrow",
  "White-throated Sparrow",
  "White-winged Dove",
  "Wild Turkey",
  "Wood Duck",
  "Yellow Warbler",
  "Yellow-bellied Sapsucker",
];
