export const birds = [
  "American Crow",
  "American Goldfinch",
  "American Robin",
  "American White Pelican",
  "Baltimore Oriole",
  "Barn Swallow",
  "Black-capped Chickadee",
  "Blue Jay",
  "Brown Thrasher",
  "Brown-headed Cowbird",
  "Canada Goose",
  "Cedar Waxwing",
  "Chipping Sparrow",
  "Common Grackle",
  "Common Yellowthroat",
  "Cooper's Hawk",
  "Dark-eyed Junco",
  "Downy Woodpecker",
  "Eastern Bluebird",
  "Eastern Phoebe",
  "European Starling",
  "Gray Catbird",
  "Great Blue Heron",
  "House Finch",
  "House Sparrow",
  "Indigo Bunting",
  "Killdeer",
  "Mallard",
  "Mourning Dove",
  "Northern Cardinal",
  "Northern Flicker",
  "Northern House Wren",
  "Northern Mockingbird",
  "Red-bellied Woodpecker",
  "Red-headed Woodpecker",
  "Red-tailed Hawk",
  "Red-winged Blackbird",
  "Ring-billed Gull",
  "Rose-breasted Grosbeak",
  "Ruby-throated Hummingbird",
  "Sandhill Crane",
  "Song Sparrow",
  "Tree Swallow",
  "White-breasted Nuthatch",
  "White-throated Sparrow",
  "Wild Turkey",
];
